name: Build and Deploy via FTP

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        app:
          - name: shell
            workspace: apps/shell
            server-dir: /public_html/shell/
          #- name: cbms
          #  workspace: apps/cbms
          #  server-dir: /public_html/cbms/
          #- name: cdts
          #  workspace: apps/cdts
          #  server-dir: /public_html/cdts/
          #- name: mfe-products-angular
          #  workspace: apps/mfe-products-angular
          #  server-dir: /public_html/mfe-products-angular/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build ${{ matrix.app.name }} app
        run: npm run build -w ${{ matrix.app.workspace }}

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: 103.38.50.181
          username: mfeftpuser
          password: ${{secrets.FTPPASSWORD}}
          local-dir: ${{ matrix.app.workspace }}/dist/
          
